language: python
python: "3.7"

env:
  global:
    - DOCKER_USERNAME: certhubci
    - secure: "UKvM4ObLRYqJtXyFu11mWhUqH3QckzcdD0FAWhK1eCn/7h0By1mIRI60q2nAalz6PmR8+5D4KaI8cNvcNJqwmd5fGgF4QX8hM0xI421QysLmj1fWkWwGulGW5kijVZjZ6O41IqIcA8MOWG7OSAco9JRGI3AE2DLVJNLjA7PIBfHIFXNtpshlHS0nGeuOoCMazKhts0k3L7/6Pnmqq1HBzTKuhYAmOidXKeYwNeDoHwWhgRIqdPEUIHcwbn2lJhmJ90yJkBLZ5Os/J0z6jDWAn/Db3sSGhLBQ3ASr6yF8QcGnruw69yk5lCpXNVI3YRsi+zxMYPnWkNeiDGkFLf7phw6b/mTd1uz8UBt7Ra1CYpNFzpOEh2niOX0DYU03rgtEMvWeaoGzeRoFwngf8Dp8SfampoGfgTnIytJhLZc0Ki4iqriqUYZ1YeqghBYF1M1Ip7MSveQQ8JKuBPT4H2ltj5/R9FW949ahFFqIR2mAvWt7JCfWTwV/asTEXKcZHyOXNL+ZKVLAPKL6eGIPhFd9Zubnss8+0Izo8p6koOYYwQFDQItn2DkZQyowtuHz7UT7UNPE/cYcMzDiWpF0TQSYOFuVwNAUWIySWf/6+AABxVK7tkRtOFNxVohrOoCkum30GAbPbPD1QPTAovftlZbX1R/HG8HpWn0auy/Q0BvRHV4="

script: .travis/push_readme.py certhub/certhub README.md
